### ISSUE TITLE
Issue with SSR

### ISSUE THREAD

**Issue by willnode** [ShahzadQ/zustand-persist-cookie-storage#1]
I got error like this with Astro framework

```
 [astro-island] Error hydrating /src/components/sidebar/navbar.tsx 
ReferenceError: __dirname is not defined
    at index.js:1:2373
    at node_modules/zustand-persist-cookie-storage/dist/index.js (index.js:1:2434)
    at __require2 (chunk-OL46QLBJ.js?v=2cef3d26:21:50)
```

It seems the bundler get buggie. If I copied the source, it works.

**Comment by shahzadq** [comment]
hi,
sorry I'm a bit new to building and bundling packages and i made this one a couple years ago i think.
Currently I'm using @vercel/ncc for the build step, could it be an issue with that?
I can switch to a different bundler like tsup if you think that'll help.

**Comment by willnode** [comment]
AFAIK ncc works well only for CJS require/exports, not ES modules.

I have no actual building packages experience but I think just using `tsc` should works.

**Comment by willnode** [comment]
For me, I end up actually copying this repo content, because I have an actual use case, like preventing CSS flashing with dark mode by reading the saved cookie during SSR. Nonetheless thank you for creating this repo!
